name: layout-switcher
version: '0.1'
summary: Layout Switcher
description: |
  Layout Switcher for X11
base: core20
confinement: devmode

parts:
  layout-switcher:
    plugin: python
    source: .
    stage-packages:
      - libx11-6
      - python3-xlib

apps:
  layout-switcher:
    command: bin/layout-switcher
    plugs:
      - x11
